name: "Bug Report"
description: Create a report to help us improve
labels: ['🐛 bug']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please [search for existing issues](https://github.com/Jaliborc/PetTracker/issues?q=is%3Aissue%20) to see if one already exists for the bug you encountered. If an issue exists but it is closed, it may be solved but not yet available in a stable release.
    options:
    - label: I have searched the existing open and closed issues.
      required: true

- type: textarea
  attributes:
    label: Description
    description: What did you expect to happen and what happened instead?
  validations:
    required: true

- type: input
  attributes:
    label: PetTracker Version
    description: |
      You can see the current version in the ingame addons list, in the CurseForge app or in the `## Version:` field of the PetTracker_X.toc file.
    placeholder: "PetTracker 4.4.4"
  validations:
    required: true

- type: dropdown
  id: flavor
  attributes:
    label: World of Warcraft Flavor
    description: What version of World of Warcraft are you running?
    options:
      - Retail
      - Classic Era
      - Cataclysm Classic
      - Beta (which one?)
  validations:
    required: true

- type: dropdown
  id: region
  attributes:
    label: World of Warcraft Region
    description: Which region are you playing World of Warcraft in?
    options:
      - EU
      - TW/Asia
      - US/NA
  validations:
    required: true

- type: dropdown
  id: interference 
  attributes:
    label: Tested with only PetTracker
    description: |
      Sometimes, addons can interfere with each other. We recommend testing with only PetTracker enabled to see if the issue persists.
    options:
      - I got this issue with only PetTracker enabled
      - This issue happens only with another specific enabled (which one?)
  validations:
    required: true

- type: textarea
  attributes:
    label: Lua Error
    description: |
      Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (type `/console scriptErrors 1` in the chat and reload the game).
      If multiple errors occur, type only the first (labelled 1/Many) that appeared.
    render: Text
  validations:
    required: false

- type: textarea
  attributes:
    label: Reproduction Steps
    description: Please list out the steps to reproduce your bug. Please verify that your reproduction steps are enough to reproduce the problem.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

- type: input
  attributes:
    label: Last Working Version
    description: |
      Was it working in a previous version? If yes, which was the last good one?
    placeholder: "PetTracker 4.4.4"
  validations:
    required: false

- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
    placeholder: Click here to attach your screenshots via the editor button in the top right.
  validations:
    required: false
